### ISSUE TITLE
Pendientes varios

### ISSUE THREAD

**Issue by juancarloscastillo** [educacion-meritocracia/market-justice-preferences-school#10]
- [x] Hipótesis school achievement @juancarloscastillo 
- [x] @Andreas-Lafferte hay que dar vuelta en el esquema las hipótesis de interacción: es el estatus lo que modera la asociación entre percepción de meritocracia y market justice (está al revés)
- [x] Y @Andreas-Lafferte , agregar también lo de school achievement en el esquema
- [x] Clarificar la fuente de los análisis de la CEP y citar la encuesta

**Comment by Andreas-Lafferte** [comment]
Perfecto, vero lo del esquema y las fuentes

**Comment by Andreas-Lafferte** [comment]
![MJP(1)](https://github.com/educacion-meritocracia/market-justice-preferences-school/assets/64297783/053d5d82-e1d0-4359-be54-b62129dc44ee)

**Comment by Andreas-Lafferte** [comment]
¿Está bien así?

**Comment by juancarloscastillo** [comment]
Un par de detalles:
- especificaría dentro del cuadtro de meritocratic perception lo de society & school, que en realidad son 2 hipótesis (H1 a y b)
- actual según la redacción actual de las hipótesis; para simplificar se elminan las bridge hipótesis y se plantean simplemente como supuestos
